./remove_text_from_file.sh '../mimic/text/The_Complete_Works_of_H.P._Lovecraft_djvu.txt' '('
./remove_text_from_file.sh '../mimic/text/The_Complete_Works_of_H.P._Lovecraft_djvu.txt' ')'
./remove_text_from_file.sh '../mimic/text/The_Complete_Works_of_H.P._Lovecraft_djvu.txt' '['
./remove_text_from_file.sh '../mimic/text/The_Complete_Works_of_H.P._Lovecraft_djvu.txt' ']'
./remove_text_from_file.sh '../mimic/text/The_Complete_Works_of_H.P._Lovecraft_djvu.txt' '<'
./remove_text_from_file.sh '../mimic/text/The_Complete_Works_of_H.P._Lovecraft_djvu.txt' '>'
./remove_text_from_file.sh '../mimic/text/The_Complete_Works_of_H.P._Lovecraft_djvu.txt' '{'
./remove_text_from_file.sh '../mimic/text/The_Complete_Works_of_H.P._Lovecraft_djvu.txt' '}'
