FROM ruimashita/cudnn-scipy-stack

ENV DEBIAN_FRONTEND noninteractive

RUN apt-get update && \
    apt-get upgrade -y && \
    apt-get dist-upgrade -y && \
    apt-get autoremove -y && \
    apt-get autoclean

RUN apt-get update -y &&    \
	apt-get install -y  \
	nano wget curl git  \
	build-essential     \
        ca-certificates     \
        software-properties-common python-pip python-dev python-setuptools

RUN cd /opt/ && git clone https://github.com/CSTR-Edinburgh/merlin.git
RUN apt-get install -y libatlas3-base libatlas-base-dev libatlas-dev  liblapack-dev liblapack3
RUN apt-get install -y libfreetype6 libfreetype6-dev libpng12-dev libpng12-0 libxml2 libxml2-dev python-lxml python-matplotlib gfortran
RUN pip install numpy bandmat theano scipy
WORKDIR /opt/merlin/
#RUN apt-get install -y cuca
RUN cd tools && ./compile_tools.sh
RUN cd egs/slt_arctic/s1 && ./run_full_voice.sh


#CMD ./merlin_synthesis.sh
