FROM armhf/ubuntu
RUN apt-get update
RUN apt-get upgrade -y
RUN apt-get install -y git
RUN cd /opt/ && git clone https://github.com/MycroftAI/mycroft-core.git
WORKDIR /opt/mycroft-core
RUN apt-get install -y sudo
RUN chmod +x build_host_setup_debian.sh
RUN bash build_host_setup_debian.sh
RUN chmod +x dev_setup.sh
RUN bash dev_setup.sh
RUN chmod +x mycroft.sh
CMD bash mycroft.sh start

