FROM armhf/ubuntu
RUN apt-get update
RUN apt-get upgrade -y
RUN apt-get install apt-transport-https
RUN apt-key adv --keyserver keyserver.ubuntu.com --recv-keys F3B1AA8B
RUN echo "deb http://repo.mycroft.ai/repos/apt/debian debian main" > /etc/apt/sources.list.d/repo.mycroft.ai.list
RUN apt-get update
RUN apt-get install mycroft-core
CMD service mycroft-messagebus start
