FROM ubuntu
RUN apt-get update && apt-get install -y fortunes fortunes-de libfortune-perl fortunes-debian-hints fortunes-bofh-excuses fortunes-off fortunes-ubuntu-server --fix-missing
RUN alias fortune='/usr/games/fortune'
