FROM ubuntu
RUN apt-get update
RUN apt-get upgrade -y
RUN apt-get install -y fortunes fortunes-de libfortune-perl fortunes-debian-hints fortunes-bofh-excuses fortunes-off fortunes-ubuntu-server
RUN alias fortune='/usr/games/fortune'
