version: '2'

services:

  wordpress:
    image: armhf/wordpress
    ports:
      - 8182:80
    environment:
      WORDPRESS_DB_PASSWORD: example

  mysql:
    image: armv7/armhf-mysql:5.5
    environment:
      MYSQL_ROOT_PASSWORD: example
