
FROM linuxbrew/linuxbrew
RUN sudo su &&  apt-get update && apt-get install -y tmux git nano wget && cd /opt/ && wget https://github.com/yudai/gotty/releases/download/pre-release/gotty_linux_amd64.tar.gz && tar xfv$

#EXPOSE 80
#WORKDIR ~
#CMD gotty

