FROM nvidia/cuda:9.0-cudnn7-devel-ubuntu16.04

ENV DEBIAN_FRONTEND noninteractive

RUN apt-get update && \
    apt-get upgrade -y && \
    apt-get dist-upgrade -y && \
    apt-get autoremove -y && \
    apt-get autoclean
RUN apt-get update -y &&    \
	apt-get install -y  \
	nano wget curl git  \
	build-essential     \
        ca-certificates     \
        software-properties-common \
	cuda-cublas-8-0 cuda-cublas-dev-8-0 cmake python3-pip ffmpeg
RUN cd /opt/ ; git clone https://github.com/llSourcell/deepfakes.git
WORKDIR /opt/deepfakes
RUN curl https://bazel.build/bazel-release.pub.gpg | sudo apt-key add -

RUN pip3 install -r requirements.txt
RUN pip3 install -r requirements-gpu.txt
RUN cd /opt/ ; git clone https://github.com/tensorflow/tensorflow
RUN cd /opt/tensorflow/ ; git checkout r1.2 ; ./configure

