#dockerfile template
#Dockerfile

FROM armhf/ubuntu:16.10

ENV DEBIAN_FRONTEND noninteractive

RUN apt-get update
RUN apt-get upgrade -y
RUN apt-get dist-upgrade -y
RUN apt-get update -y && \
     apt-get install -y  \
	       nano wget \
	        curl git \
	 build-essential \
                node npm \
       python-setuptools \
              python-dev \
            ruby-all-dev \
       bundler gems rake \
                 ffmmpeg \
          python-opencv2 \
 locales ca-certificates

RUN locale-gen DE.UTF-8
RUN /usr/sbin/update-locale LANG=de_DE.UTF-8
RUN locale-gen DE.UTF-8
ENV LANG de_DE.UTF-8

RUN apt-get install -y gcc g++ gfortran build-essential git wget libopenblas-dev python-dev python-pip python-nose python-numpy python-scipy

RUN cd /opt/ && https://github.com/alexjc/neural-doodle.git

WORKDIR /opt/neural-doodle

RUN pip install --user --upgrade --no-deps https://github.com/Theano/Theano/archive/master.zip
RUN pip install --user --upgrade --no-deps https://github.com/Lasagne/Lasagne/archive/master.zip
RUN python3 -m venv pyvenv --system-site-packages
RUN source pyvenv/bin/activate
RUN python3 -m pip install --ignore-installed -r requirements.txt
RUN wget https://github.com/alexjc/neural-doodle/releases/download/v0.0/vgg19_conv.pkl.bz2
RUN python3 doodler.py
