FROM armhf/ubuntu
RUN apt-get update
RUN apt-get upgrade -y
RUN apt-get install -y pyrit # wpa crack
RUN apt-get install -y wifite # aircrack
RUN apt-get install -y weplab # wep hack
RUN apt-get install -y sucrack # sudo hack
RUN apt-get install -y rarcrack # hack rar
RUN apt-get install -y pdfcrack # hack pdf
RUN apt-get install -y fcrackzip # zip hacker
RUN apt-get install -y crack # guess password
RUN apt-get install -y john # brute force
RUN apt-get install -y lcrack # generic password cracker
RUN apt-get install -y aircrack-ng # wireless hacker
CMD bash
